import "./globals.css";
import Providers from "@/components/providers";
import { Inter } from "next/font/google";
// import 'tw-elements/dist/css/tw-elements.min.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh">
      {/* <Script
				type='text/javascript'
				src='@/node_modules/tw-elements/dist/js/tw-elements.umd.min.js'
			/> */}
      <Providers>
        <body className={inter.className}>{children}</body>
      </Providers>
    </html>
  );
}
